In [2]:
class Employee:
    emp_count = 0

    def __init__(self, n, f, s, d):
        self.n = n
        self.f = f
        self.s = s
        self.d = d
        Employee.emp_count += 1

    @staticmethod
    def avg_salary(emps):
        total_s = sum(emp.s for emp in emps)
        return total_s / len(emps) if len(emps) > 0 else 0

class FulltimeEmployee(Employee):
    def __init__(self, n, f, s, d):
        super().__init__(n, f, s, d)

# Create instances of Employee class
e1 = Employee("John ", "Spouse & 2 kids", 60000, "HR")
e2 = Employee("Jane ", "Partner & 1 kid", 75000, "Finance")
e3 = Employee("Michael ", "Single", 50000, "IT")

# Create instances of FulltimeEmployee class
fte1 = FulltimeEmployee("Alice ", "Spouse", 80000, "Marketing")
fte2 = FulltimeEmployee("Robert ", "Single", 70000, "Sales")

# Call member functions
emp_list = [e1, e2, e3]
fte_list = [fte1, fte2]

avg_sal_all = Employee.avg_salary(emp_list)
avg_sal_fulltime = Employee.avg_salary(fte_list)

print("Average Salary of All Employees:", avg_sal_all)
print("Average Salary of Fulltime Employees:", avg_sal_fulltime)
print("Total Employee Count:", Employee.emp_count)


Average Salary of All Employees: 61666.666666666664
Average Salary of Fulltime Employees: 75000.0
Total Employee Count: 5


In [ ]:
import numpy as np
random_vector = np.random.uniform(1, 20, size=20)
print("Original array:")
print(random_vector)

reshaped_array = random_vector.reshape(4, 5)

max_indices = np.argmax(reshaped_array, axis=1)

reshaped_array[np.arange(4), max_indices] = 0

print("\nReshaped array:")
print(reshaped_array)


Original array:
[ 2.35104668 13.2579605  18.30664635  1.19127204  2.41996359 13.59967525
 15.27520732 12.29234851  2.14092215  7.62587702 11.64479036 14.07696663
 17.36751437  5.74298434 16.68339783  9.30785615 10.90069013 15.37107566
  4.75717622 19.23561929]

Reshaped array:
[[ 2.35104668 13.2579605   0.          1.19127204  2.41996359]
 [13.59967525  0.         12.29234851  2.14092215  7.62587702]
 [11.64479036 14.07696663  0.          5.74298434 16.68339783]
 [ 9.30785615 10.90069013 15.37107566  4.75717622  0.        ]]
